# Generated by Django 4.1.1 on 2022-11-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='User_reset_p_f74d5e_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmation_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmation_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_sent_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unconfirmed_email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='btc_wallet_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='network_wallet_address',
        ),
    ]
